name: CI / CHANGELOG

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  require-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Diff Files
        run: |
            if [[ -z $(git diff --name-only origin/main .changes) ]]; then
              echo "No changes detected. Failing the action."
              exit 1
            fi
