name: CI / Python / pre-commit

on:
  push:

env:
  KEY_PREFIX: base-env
  PRE_COMMIT_CACHE: ~/.cache/pre-commit

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4.1.0

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          # Install a specific version of uv.
          version: "0.4.10"

      - name: Set up Python using .python-version
        id: python
        uses: actions/setup-python@v5.2.0
        with:
          # don't have to supply, would auto resolve to this otherwise
          python-version-file: .python-version

      - name: Restore uv cache
        id: uv-cache
        uses: actions/cache@v4.0.2
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install Python dependencies
        if: steps.uv-cache.outputs.cache-hit != 'true'
        run: uv sync --dev --all-extras

      - name: Run pre-commit
        run: uv run pre-commit run --hook-stage manual --all-files >> $GITHUB_STEP_SUMMARY

      - name: Minimize uv cache
        run: uv cache prune --ci
